#! /bin/bash

case "$(xset -q|grep LED| awk '{ print $10 }')" in
    "00000000") KBD="󰬵  pt" ;;
    "00000002") KBD="󰬵  pt" ;;
    "00000001") KBD="󰬶  PT" ;;
    "00000003") KBD="󰬶  PT" ;;
    "00001000") KBD="󰬵  ελ" ;;
    "00001002") KBD="󰬵  ελ" ;;
    "00001001") KBD="󰬶  ΕΛ" ;;
    "00001003") KBD="󰬶  ΕΛ" ;;
    *) KBD="unknown" ;;
esac

echo $KBD
