#! /usr/bin/env bash

let MUS=playerctl metadata |\
    sed "s/  \+/\t/g;s/\t\t/\t/g"  |\
    cut --delimiter=$'\t' -f 2 |\
    awk 'NR>3 && NR < 7 {print}' |\
    tr '\n' '|' |\
    sed 's/|/ | /g; s/| $/\n/g';

case "$(playerctl status 2> /dev/null)" in
    ""|"Stopped") echo "   󰝛   " ;;
    "Playing")
        TITLE=$(playerctl metadata title);
        ARTIST=$(playerctl metadata artist);
        if [ ${#TITLE} -ge 50 ]; then
            TITLE="${TITLE:0:50}…";
        fi
        echo " $TITLE | $ARTIST" ;; # | $ALBUM" ;;
    "Paused")
        TITLE=$(playerctl metadata title);
        ARTIST=$(playerctl metadata artist);
        if [ ${#TITLE} -ge 50 ]; then
            TITLE="${TITLE:0:50}…";
        fi
        echo "󰏤 $TITLE | $ARTIST" ;; # | $ALBUM" ;;
esac
