[colors.bright]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x1d2021"
foreground = "0xd4be98"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "FiraCode Nerdfont"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
opacity = 0.8
title = "Alacritty"

[window.padding]
x = 15
y = 15
