#! /bin/bash

case "$(xset -q|grep LED| awk '{ print $10 }')" in
    "00000000") KBD="pt 🇧🇷" ;;
    "00000002") KBD="pt 🇧🇷" ;;
    "00001000") KBD="grc 🇬🇷" ;;
    "00001002") KBD="grc 🇬🇷" ;;
    *) KBD="unknown" ;;
esac

echo $KBD
