#! /usr/bin/env bash

###### Variables ######
LABEL="${LABEL:- }"
LOCATION="${LOCATION:- }"
FONT="${FONT:-Mononoki Nerd Font 10}"
BAR_POSITION="${BAR_POSITION:-bottom}"

###### Variables ######


###### Functions ######
# print the full weather
# see https://github.com/chubin/wttr.in#usage for full configuration options
print_weather_report() {
  if [[ $LOCATION != " " ]]; then
    curl  -H "Accept-language: pt-br" -s "https://wttr.in/$LOCATION?T"
  else
    curl -H "Accept-language: pt-br" -s "https://wttr.in/?T"
  fi
}

# print the one line weather
# see https://github.com/chubin/wttr.in#one-line-output for formatting options
print_weather_line() {
  if [[ $LOCATION != " " ]]; then
    curl -s https://wttr.in/${LOCATION}?lang=pt-br?u\&format="%c+%t++%w" | tr -d \"
  else
    curl -s 'https://wttr.in/?lang=pt-br?u\&format="%c+%t++%w"' | tr -d \"
  fi
}

###### Functions ######


###### Main body ######

# handle any click
# rofi pop up
case "$BLOCK_BUTTON" in
  1|2|3)
      IFS=
      weather_report=$(print_weather_report)

      # check bar position and adjust anchor accordingly
      if [[ $BAR_POSITION = "top" ]]; then
        anchor="northeast"
      else
        anchor="southeast"
      fi

      # open rofi
      # (add the following option to rofi command with proper config file, if needed)
      echo $weather_report \
        | rofi \
            -dmenu \
            -markup-rows \
            -font $FONT \
            -m -3 \
            -theme-str 'window {width: 60%; anchor: '"$anchor"'; location: northwest;}' \
            -theme-str 'listview {lines: '"$(echo $weather_report | wc -l)"' ;scrollbar: false;}' \
            -theme "gruvbox-dark-hard" \
            -p "Clima"
esac

# print blocklet text

if [[ $LABEL != " " ]]; then
  echo $LABEL$(print_weather_line)
else
  echo $(print_weather_line)
fi

###### Main body ######
