#! /bin/bash
session="blog"

# Check if the session exists, discarding output
# We can check $? for the exit status (zero for success, non-zero for failure)
tmux has-session -t $session 2>/dev/null

if [ $? != 0 ]; then
  # Set up your session
    tmux new-session -d -s $session -n "editor" -c ~/proj/caiogeraldes.gitlab.io
    tmux neww -a -t $session -n "server" -c ~/proj/caiogeraldes.gitlab.io "hugo server"
    tmux select-window -t "server"
    tmux split-window -v
    tmux neww -a -t $session -n "arquivos" "ranger"
    tmux select-window -t "editor"
fi

tmux -2 attach-session -t $session

