#!/bin/bash

if [ "$@" ]; then
    echo "$@" | cut -d$'\t' -f1 | xargs -L1 bt activate
else
    active_window=`bt active | \grep firefox | awk '{print $1}'`
    selected=`bt list \
        | rofi -dmenu -i -multi-select -select "$active_window" -p "Activate tab"  \
        | cut -d$'\t' -f1`
    if [ "$selected" ]; then
        echo "$selected" | xargs -L1 bt activate
    fi
fi
