#! /bin/bash

if [ $1 -eq $1 2>/dev/null ] && [ $2 -eq $2 2>/dev/null ] && [ $1 -gt 0 ] && [ $2 -gt 0 ]
then
	## Obtém o volume no qual o hino está
	if [ $1 -lt 4 ]; then
		livro="geldner1.pdf"
	elif [ $1 -gt 8 ]; then
		livro="geldner3.pdf"
	else
		livro="geldner2.pdf"
	fi
		
		pagina=$(cat ~/.scripts/geldnermap | grep -P $1'\t'$2'\t'| awk '{print $3}')
		zathura -P $pagina /home/silenus/docs/Línguas/Indo-Europeias/Védico/Traduções/$livro &
else
    echo "Insira um valor válido."
fi




