#! /bin/bash

if [ $1 -eq $1 2>/dev/null ] && [ $2 -eq $2 2>/dev/null ] && [ $1 -gt 0 ] && [ $2 -gt 0 ]
then
	livro="jamison.pdf"
	pagina=$(cat $HOME/.scripts/jamisonmap | grep -P $1'\t'$2'\t'| awk '{print $3}')
	zathura -P $pagina /home/silenus/docs/Línguas/Indo-Europeias/Védico/Traduções/$livro &
else
    echo "Insira um valor válido."
fi

