#! /bin/bash

if [ $1 -eq $1 2>/dev/null ] && [ $2 -eq $2 2>/dev/null ] && [ $1 -gt 0 ] && [ $2 -gt 0 ]
then
	if [ $2 -lt 10 ]
	then
		if [ $1 -lt 10 ] 
		then	
		echo "Touch"
			link="https://liberalarts.utexas.edu/lrc/rigveda/RV0$1.php#H00$2"	
		else
			link="https://liberalarts.utexas.edu/lrc/rigveda/RV10.php#H00$2"
		fi

	elif [ $2 -lt 100 ]
	then
		if [ $1 -lt 10 ] 
		then	
			link="https://liberalarts.utexas.edu/lrc/rigveda/RV0$1.php#H0$2"	
		else
			link="https://liberalarts.utexas.edu/lrc/rigveda/RV10.php#H0$2"
		fi
	else
		if [ $1 -lt 10 ] 
		then	
			link="https://liberalarts.utexas.edu/lrc/rigveda/RV0$1.php#H$2"
		else
			link="https://liberalarts.utexas.edu/lrc/rigveda/RV10.php#H$2"
		fi
	fi
	firefox $link &
else
    echo "Insira um valor válido."
fi



