#! /usr/bin/env python

import sys
import os
import betacode.conv 
import clipboard

if sys.argv[1] == "m":
    os.system("firefox http://www.perseus.tufts.edu/hopper/morph?l=" + sys.argv[2] + "&la=greek#lexicon")
    print(sys.argv)
else:
    #entrada = sys.argv[1]
    os.system("firefox http://www.perseus.tufts.edu/hopper/morph?l=" + sys.argv[1] + "&la=greek#lexicon")
    #os.system("firefox http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.04.0057%3Aentry%3D" + entrada)


