#! /usr/bin/env python

import sys
import os
import betacode.conv 
import clipboard

entrada = "http://solo.bodleian.ox.ac.uk/primo-explore/search?query=any,contains," + sys.argv[1] + "&tab=local&search_scope=LSCOP_ALL&vid=SOLO&lang=en_US&offset=0"
print(entrada)

# os.system("firefox ")

